"""Version identifiers frozen for the first Neo memory contract."""

CONTRACT_VERSION = "neo.memory.contract.v1"
POLICY_VERSION = "neo.memory.policy.v1"
TAXONOMY_VERSION = "neo.memory.taxonomy.v1"
RECALL_CONTRACT_VERSION = "neo.memory.recall.v1"
LEXICAL_SCORING_VERSION = "neo.memory.lexical.bm25.v1"
PROMPT_SERIALIZER_VERSION = "neo.memory.prompt.v1"
OUTBOX_PROCESSING_VERSION = "neo.memory.outbox.v1"
DERIVED_DOCUMENT_VERSION = "neo.memory.derived-document.v1"
EMBEDDING_DOCUMENT_VERSION = "neo.memory.embedding-document.v1"
EMBEDDING_IDENTITY_VERSION = "neo.memory.embedding-identity.v1"
VECTOR_METADATA_VERSION = "neo.memory.vector-metadata.v1"
SEMANTIC_SCORING_VERSION = "neo.memory.semantic-hybrid.v1"
RECONCILIATION_POLICY_VERSION = "neo.memory.reconciliation.v1"
RETRY_POLICY_VERSION = "neo.memory.retry.v1"
