import { useEffect, useState } from "react";
import { api } from "./api.js";

export default function Bundles() {
  const [exports, setExports] = useState([]); const [imports, setImports] = useState([]);
  const [file, setFile] = useState(null); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false); const [detail, setDetail] = useState(null);
  const load = () => Promise.all([api.bundleExports(), api.bundleImports()]).then(([left, right]) => { setExports(left.exports || []); setImports(right.imports || []); });
  useEffect(() => { load().catch((error) => setStatus(error.message)); }, []);
  async function validate() { if (!file) return; setBusy(true); try { const result = await api.validateBundle(file); setStatus(result.valid ? "Bundle is valid. Import stores it as inert archive-only data." : "Validation failed."); } catch (error) { setStatus(`Validation error: ${error.message}`); } finally { setBusy(false); } }
  async function archive() { if (!file || !window.confirm("Archive this bundle as inert data? No patches, tests, checkpoints, or repository writes will execute.")) return; setBusy(true); try { await api.importBundle(file); await load(); setStatus("Bundle archived. Imported records are view-only metadata."); } catch (error) { setStatus(`Import error: ${error.message}`); } finally { setBusy(false); } }
  async function showExport(item) { try { setDetail((await api.bundleExport(item.id)).bundle); } catch (error) { setStatus(error.message); } }
  async function showImport(item) { try { setDetail((await api.bundleImport(item.id)).bundle); } catch (error) { setStatus(error.message); } }
  const entities = detail?.metadata?.manifest?.entities || {};
  return <section className="settings-section"><h2>Bundles</h2><p className="dialog-caption">Portable sanitized evidence bundles. Imports are archive-only and never execute actions.</p><p className="task-help">Secrets and original absolute host paths are redacted before export.</p><label>Bundle file<input type="file" accept=".zip,.neo.zip" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><div className="settings-actions"><button className="neo-button" disabled={!file || busy} onClick={validate}>Validate import</button><button className="neo-button" disabled={!file || busy} onClick={archive}>Import archive-only</button></div>{status ? <p className="settings-status">{status}</p> : null}<h3>Export history</h3>{exports.length ? <ul>{exports.map((item) => <li key={item.id}><button type="button" onClick={() => showExport(item)}>{item.bundle_type} · {item.root_entity_id}</button> · <a href={`/api/bundles/exports/${item.id}/download`}>Download</a></li>)}</ul> : <p>No exports yet.</p>}<h3>Imported archives</h3>{imports.length ? <ul>{imports.map((item) => <li key={item.id}><button type="button" onClick={() => showImport(item)}>{item.file_name} · {item.status}</button> {item.warnings?.length ? `· ${item.warnings.join(" ")}` : ""}</li>)}</ul> : <p>No imports yet.</p>}{detail ? <section className="bundle-detail"><h3>Bundle detail</h3><p><strong>{detail.file_name}</strong> · {detail.status} · {detail.size_bytes} bytes</p><p className="task-help">Archive-only records are readable evidence; they do not execute actions.</p><h4>Included summaries</h4><ul>{Object.entries(entities).map(([name, items]) => <li key={name}>{name.replaceAll("_", " ")}: {Array.isArray(items) ? items.length : 0}</li>)}</ul><h4>Timeline</h4>{entities.recovery_events?.length ? <ol>{entities.recovery_events.map((item) => <li key={item.id}>{item.event_type} · {item.created_at}</li>)}</ol> : <p>No recovery events included.</p>}<h4>Artifacts, tests, and checkpoints</h4><p>{entities.patch_applications?.length || 0} patch records · {entities.test_runs?.length || 0} test runs · {entities.git_checkpoints?.length || 0} checkpoints</p></section> : null}</section>;
}
