import { useEffect, useState } from "react";
import { api } from "./api.js";

export default function CommandSandbox() {
  const [workspaceId, setWorkspaceId] = useState(""); const [command, setCommand] = useState("python -m pytest -q"); const [category, setCategory] = useState("test");
  const [runs, setRuns] = useState([]); const [policy, setPolicy] = useState(null); const [detail, setDetail] = useState(null); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => setRuns((await api.commandRuns()).runs || []);
  useEffect(() => { load().catch((error) => setStatus(error.message)); }, []);
  const payload = () => ({ workspace_id: workspaceId, command: command.trim().split(/\s+/).filter(Boolean), cwd: ".", category, created_by: "user" });
  async function validate() { setBusy(true); try { setPolicy(await api.validateCommand(payload())); } catch (error) { setStatus(error.message); } finally { setBusy(false); } }
  async function propose() { setBusy(true); try { const run = await api.proposeCommand(payload()); setDetail(run); setPolicy(run.policy_decision); await load(); setStatus(run.status === "blocked" ? "Blocked command recorded in audit history." : "Command proposed; explicit approval is required."); } catch (error) { setStatus(error.message); } finally { setBusy(false); } }
  async function approve(item) { setBusy(true); try { const next = await api.approveCommand(item.id); setDetail(next); await load(); setStatus("Approved. Execution remains a separate action."); } catch (error) { setStatus(error.message); } finally { setBusy(false); } }
  async function execute(item) { if (!window.confirm("Execute this approved allowlisted command only inside Neo's managed workspace?")) return; setBusy(true); try { const next = await api.executeCommand(item.id); setDetail(next); await load(); setStatus("Command completed; output is redacted and bounded."); } catch (error) { setStatus(error.message); } finally { setBusy(false); } }
  const policyMessage = policy?.allowed
    ? (typeof policy.reason === "string" ? policy.reason : "Command allowed; explicit approval required.")
    : (policy?.blocked_reasons || []).join("; ");
  return <section className="settings-section"><h2>Command Sandbox</h2><p className="dialog-caption">Commands run only in managed workspaces. Package installs, remote Git, sudo, destructive commands, and secret dumping are blocked.</p><label>Managed workspace ID<input value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)} /></label><label>Command argv<input value={command} onChange={(event) => setCommand(event.target.value)} /></label><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="read_only">read-only</option><option value="test">test</option><option value="build">build</option></select></label><div className="settings-actions"><button className="neo-button" disabled={busy} onClick={validate}>Validate</button><button className="neo-button" disabled={busy} onClick={propose}>Propose command</button></div>{policy ? <p className={policy.allowed ? "settings-status" : "settings-error"}>{policyMessage}</p> : null}{status ? <p className="settings-status">{status}</p> : null}<h3>Run history</h3>{runs.length ? <ul>{runs.map((item) => <li key={item.id}><button type="button" onClick={() => setDetail(item)}>{item.category} · {item.command.join(" ")}</button> · {item.status} {item.status === "proposed" ? <button onClick={() => approve(item)}>Approve</button> : null} {item.status === "approved" ? <button onClick={() => execute(item)}>Execute</button> : null}</li>)}</ul> : <p>No command runs yet.</p>}{detail ? <section className="bundle-detail"><h3>Command detail</h3><p>{detail.command?.join(" ")} · {detail.status} · exit {detail.exit_code ?? "—"}</p><p>{detail.policy_decision?.reason}</p><pre>{detail.stdout_text || detail.stderr_text || "No execution output."}</pre><p className="task-help">Output is truncated at 64KB and redacted before storage.</p></section> : null}</section>;
}
