import { useEffect, useState } from "react";
import { api } from "./api.js";

const scopes = ["chat", "agent_run", "coding_run", "task", "project", "repo_workspace"];
const payload = (scope_type, scope_id) => ({ scope_type, scope_id, mode: "safe", max_summary_tokens: 1200, include_events: true, include_files: true, include_tests: true, include_checkpoints: true });

export default function ContextMemory() {
  const [summaries, setSummaries] = useState([]); const [scopeType, setScopeType] = useState("task"); const [scopeId, setScopeId] = useState("");
  const [preview, setPreview] = useState(null); const [detail, setDetail] = useState(null); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => setSummaries((await api.contextSummaries()).summaries || []);
  useEffect(() => { load().catch((error) => setStatus(error.message)); }, []);
  async function doPreview() { if (!scopeId.trim()) return setStatus("Enter a scope id."); setBusy(true); try { setPreview(await api.contextPreview(payload(scopeType, scopeId))); setStatus("Preview is deterministic and redacted; it has not been saved."); } catch (error) { setStatus(error.message); } finally { setBusy(false); } }
  async function compact() { if (!scopeId.trim() || !window.confirm("Save this redacted context summary? It never executes actions.")) return; setBusy(true); try { const item = await api.compactContext(payload(scopeType, scopeId)); setDetail(item); setPreview(item); await load(); setStatus("Context summary saved."); } catch (error) { setStatus(error.message); } finally { setBusy(false); } }
  async function show(item) { try { setDetail((await api.contextSummary(item.id)).summary); } catch (error) { setStatus(error.message); } }
  const shown = detail || preview;
  return <section className="settings-section"><h2>Context Memory</h2><p className="dialog-caption">Durable, structured summaries for long-running work. Summaries supplement source data and never execute actions.</p><div className="settings-row"><label>Scope<select value={scopeType} onChange={(event) => setScopeType(event.target.value)}>{scopes.map((scope) => <option key={scope}>{scope}</option>)}</select></label><label>Scope ID<input value={scopeId} onChange={(event) => setScopeId(event.target.value)} placeholder="task, run, or project id" /></label></div><div className="settings-actions"><button className="neo-button" disabled={busy} onClick={doPreview}>Preview compact summary</button><button className="neo-button" disabled={busy} onClick={compact}>Compact and save</button></div>{status ? <p className="settings-status">{status}</p> : null}<h3>Summary list</h3>{summaries.length ? <ul>{summaries.map((item) => <li key={item.id}><button type="button" onClick={() => show(item)}>{item.scope_type} · {item.scope_id}</button> · {item.token_estimate_before} → {item.token_estimate_after} tokens</li>)}</ul> : <p>No compacted summaries yet.</p>}{shown ? <section className="bundle-detail"><h3>Summary detail</h3><p>{shown.summary_text}</p><p><strong>Compression:</strong> {shown.token_estimate_before} → {shown.token_estimate_after} tokens ({shown.compression_ratio || "saved"}×)</p><h4>Decisions</h4><ul>{(shown.decisions || []).map((item, i) => <li key={i}>{item}</li>)}</ul><h4>Constraints and open items</h4><ul>{[...(shown.constraints || []), ...(shown.open_items || [])].map((item, i) => <li key={i}>{item}</li>)}</ul><p>{(shown.files || []).length} files · {(shown.tests || []).length} tests · {(shown.checkpoints || []).length} checkpoints</p><p className="task-help">Redaction: credentials and absolute host paths are removed.</p></section> : null}</section>;
}
