import { useEffect, useState } from "react";
import { api } from "./api.js";

export default function GitHub({ onClose }) {
  const [connections, setConnections] = useState([]); const [items, setItems] = useState([]); const [operations, setOperations] = useState([]); const [message, setMessage] = useState(""); const [form, setForm] = useState({name:"",owner:"",repo:"",token_ref:"GITHUB_TOKEN"}); const [number, setNumber] = useState("");
  const load=()=>Promise.all([api.githubConnections(),api.githubItems(),api.githubOperations()]).then(([a,b,c])=>{setConnections(a.connections||[]);setItems(b.items||[]);setOperations(c.operations||[]);});
  useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
  async function create(event){event.preventDefault();try{await api.createGithubConnection(form);setForm({name:"",owner:"",repo:"",token_ref:"GITHUB_TOKEN"});await load();}catch(e){setMessage(e.message);}}
  async function action(work){try{const result=await work();setMessage(result.operation?.error || "Operation recorded safely.");await load();}catch(e){setMessage(e.message);}}
  return <section className="settings-section"><h2>GitHub</h2><p className="dialog-caption">Read-only import by default. Write actions require approval; Neo never pushes, comments, merges, or closes items automatically.</p><p className="task-help">Tokens are read from environment references only and are never displayed.</p><form onSubmit={create}><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Owner<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})} required/></label><label>Repository<input value={form.repo} onChange={e=>setForm({...form,repo:e.target.value})} required/></label><label>Token environment reference<input value={form.token_ref} onChange={e=>setForm({...form,token_ref:e.target.value})} required/></label><button className="neo-button">Add connection</button></form>{connections.map(c=><div key={c.id} className="agent-run-card"><strong>{c.name}</strong> · {c.owner}/{c.repo} · {c.token_ref}<div><button onClick={()=>action(()=>api.githubHealth(c.id))}>Health</button><input aria-label={`Import number for ${c.name}`} value={number} onChange={e=>setNumber(e.target.value)} placeholder="Issue / PR #"/><button disabled={!number} onClick={()=>action(()=>api.importGithubIssue(c.id,number))}>Import issue</button><button disabled={!number} onClick={()=>action(()=>api.importGithubPr(c.id,number))}>Import PR</button></div></div>)}<h3>Imported items</h3>{items.map(i=><div key={i.id}><strong>{i.item_type} #{i.github_number}</strong> · {i.title} {i.item_type==="issue"&&!i.imported_task_id?<button onClick={()=>action(()=>api.githubCreateTask(i.id))}>Create task</button>:null}</div>)}<h3>Operation history</h3>{operations.map(o=><div key={o.id}>{o.operation_type} · {o.status}{o.error?` · ${o.error}`:""}</div>)}{message?<p className="settings-status">{message}</p>:null}<button onClick={onClose}>Close</button></section>;
}
