import { useEffect, useState } from "react";
import { api } from "./api.js";

const types = ["decision", "constraint", "summary", "failure", "fix", "test_result", "checkpoint", "file_context", "project_note", "research_finding", "user_instruction", "open_item", "completed_item", "safety_note"];

export default function MemoryRetrieval() {
  const [query, setQuery] = useState(""); const [scopeType, setScopeType] = useState(""); const [scopeId, setScopeId] = useState(""); const [type, setType] = useState("");
  const [results, setResults] = useState([]); const [items, setItems] = useState([]); const [audits, setAudits] = useState([]); const [detail, setDetail] = useState(null); const [prune, setPrune] = useState(null); const [status, setStatus] = useState("");
  const load = async () => { const [memory, retrievals] = await Promise.all([api.memoryItems(), api.memoryRetrievals()]); setItems(memory.items || []); setAudits(retrievals.retrievals || []); };
  useEffect(() => { load().catch((error) => setStatus(error.message)); }, []);
  async function search() { if (!query.trim()) return setStatus("Enter a retrieval query."); try { const value = await api.retrieveMemory({ query, scope_type: scopeType || null, scope_id: scopeId || null, memory_types: type ? [type] : [], include_score_breakdown: true }); setResults(value.results || []); setAudits((previous) => [value.retrieval, ...previous]); setStatus(`Retrieved ${value.results?.length || 0} redacted memory item(s).`); } catch (error) { setStatus(error.message); } }
  async function index() { try { const value = await api.indexMemory({ scope_type: scopeType || null, scope_id: scopeId || null }); await load(); setStatus(`Indexed ${value.indexed} context-memory item(s).`); } catch (error) { setStatus(error.message); } }
  async function previewPrune() { try { setPrune(await api.memoryPrunePreview({ stale_days: 180 })); } catch (error) { setStatus(error.message); } }
  return <section className="settings-section memory-retrieval"><h2>Memory Retrieval</h2><p className="dialog-caption">Hybrid FTS and structured retrieval. Stored text is redacted before persistence and never overrides current instructions.</p><div className="settings-row"><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="What failed last time?" /></label><label>Scope type<input value={scopeType} onChange={(event) => setScopeType(event.target.value)} placeholder="project, task, coding_run" /></label><label>Scope ID<input value={scopeId} onChange={(event) => setScopeId(event.target.value)} /></label><label>Memory type<select value={type} onChange={(event) => setType(event.target.value)}><option value="">All types</option>{types.map((value) => <option key={value}>{value}</option>)}</select></label></div><div className="settings-actions"><button className="neo-button" onClick={search}>Retrieve memories</button><button className="neo-button" onClick={index}>Index context summaries</button><button className="neo-button" onClick={previewPrune}>Preview pruning</button></div>{status ? <p className="settings-status">{status}</p> : null}<h3>Results</h3>{results.length ? <div className="memory-results">{results.map((item) => <button type="button" key={item.memory_id} onClick={async () => setDetail(await api.memoryItem(item.memory_id))}><strong>{item.title}</strong><span>{item.memory_type} · score {item.score}</span><small>{item.snippet}</small><code>{JSON.stringify(item.score_breakdown)}</code></button>)}</div> : <p>No retrieval results yet.</p>}{detail ? <section className="bundle-detail"><h3>{detail.title}</h3><p>{detail.content_text}</p><p>{detail.memory_type} · {detail.scope_type}:{detail.scope_id} · source {detail.source_type}</p><p className="task-help">Redaction summary: {detail.redaction_summary?.redacted ? "content was redacted" : "no sensitive values detected"}.</p></section> : null}<h3>Retrieval audit</h3><ul>{audits.slice(0, 10).map((audit) => <li key={audit.id}>{audit.query_text} · {audit.results?.length || 0} result(s) · {audit.created_at}</li>)}</ul><h3>Indexed memories</h3><p>{items.length} item(s) available. Source links are retained as IDs only; no host paths are shown.</p>{prune ? <section className="bundle-detail"><h3>Pruning preview</h3><p>{prune.total} eligible item(s); user instructions and safety notes are protected.</p><ul>{prune.candidates.map((item) => <li key={item.id}>{item.title} · {item.reason}</li>)}</ul></section> : null}</section>;
}
