import { useEffect, useState } from "react";
import { api } from "./api.js";

export default function WebSearch() {
  const [query, setQuery] = useState(""); const [mode, setMode] = useState("research"); const [fresh, setFresh] = useState(false);
  const [plan, setPlan] = useState(null); const [detail, setDetail] = useState(null); const [runs, setRuns] = useState([]); const [cache, setCache] = useState([]); const [message, setMessage] = useState("");
  const load = async () => { setRuns((await api.webSearchRuns()).runs || []); setCache((await api.webSearchCache()).cache || []); };
  useEffect(() => { load().catch((error) => setMessage(error.message)); }, []);
  async function preview() { try { setPlan(await api.webSearchPlan({ query, mode, freshness_required: fresh })); } catch (error) { setMessage(error.message); } }
  async function run() { try { const value = await api.webSearchRun({ query, mode, freshness_required: fresh, fetch_sources: true, include_conflict_detection: true }); setDetail(value); await load(); setMessage(value.status === "degraded" ? "Search is disabled or unavailable; the audit was preserved." : "Search evidence bundle created."); } catch (error) { setMessage(error.message); } }
  return <section className="settings-section"><h2>Web Search</h2><p className="dialog-caption">Plans, sources, evidence, citations, and uncertainty. Search never executes code or bypasses approvals.</p><label>Query<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Current library API behavior" /></label><div className="settings-row"><label>Mode<select value={mode} onChange={(event) => setMode(event.target.value)}><option value="research">Research</option><option value="technical">Technical</option><option value="general">General</option></select></label><label><input type="checkbox" checked={fresh} onChange={(event) => setFresh(event.target.checked)} /> Freshness required</label></div><div className="settings-actions"><button className="neo-button" disabled={!query.trim()} onClick={preview}>Preview plan</button><button className="neo-button" disabled={!query.trim()} onClick={run}>Run search</button></div>{message ? <p className="settings-status">{message}</p> : null}{plan ? <section className="bundle-detail"><h3>Search plan</h3><ul>{plan.queries.map((item, index) => <li key={index}>{item.purpose}: {item.query}</li>)}</ul></section> : null}{detail ? <section className="bundle-detail"><h3>Evidence bundle · {detail.status}</h3><p>{detail.summary_text || detail.error}</p><h4>Sources</h4><ul>{(detail.sources || []).map((item) => <li key={item.id}><a href={item.canonical_url} target="_blank" rel="noreferrer">{item.title}</a> · score {item.final_score}<pre>{JSON.stringify(item.metadata?.score_breakdown || { relevance: item.relevance_score, credibility: item.credibility_score, freshness: item.freshness_score }, null, 2)}</pre></li>)}</ul><h4>Evidence and citations</h4><ul>{(detail.evidence || []).map((item) => <li key={item.id}>{item.citation_label} {item.evidence_text}</li>)}</ul><h4>Conflicts</h4><ul>{(detail.conflicts || []).map((item) => <li key={item.id}>{item.topic}: {item.claim_a} / {item.claim_b}</li>)}</ul></section> : null}<h3>Cache status</h3><p>{cache.length} safe source cache {cache.length === 1 ? "entry" : "entries"}.</p><h3>Run history</h3><ul>{runs.slice(0, 10).map((item) => <li key={item.id}><button type="button" onClick={async () => setDetail(await api.webSearchRunDetail(item.id))}>{item.query_text}</button> · {item.status}</li>)}</ul></section>;
}
