from sqlalchemy import CheckConstraint, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.models.mixins import TimestampMixin


class Reflection(TimestampMixin, Base):
    """Higher-level insight generated by the reflection engine."""

    __tablename__ = "reflections"
    __table_args__ = (
        CheckConstraint("importance >= 1 AND importance <= 10", name="ck_reflections_importance"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    reflection: Mapped[str] = mapped_column(Text, nullable=False)
    importance: Mapped[int] = mapped_column(Integer, nullable=False, default=5)
